IF EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'HOADON')
drop table HOADON;
CREATE TABLE HOADON
(
   SOHD INT PRIMARY KEY,
   NGHD NVARCHAR(30) NOT NULL,
   MAKH NVARCHAR(30) NOT NULL,
   MANV INT,
   TRIGIA INT
);
GO


alter table HOADON
add toan NVARCHAR(30) NOT NULL;

alter table HOADON
ALTER  column toan NVARCHAR(90) NOT NULL;

alter table HOADON
drop  column toan;

alter table HOADON
add  THU NVARCHAR(90) NOT NULL;

SELECT * FROM HOADON;