SELECT ACCOUNT_ID, AVAIL_BALANCE, [STATUS] FROM ACCOUNT WHERE AVAIL_BALANCE >= 500 AND AVAIL_BALANCE <= 1000

SELECT ACCOUNT_ID, AVAIL_BALANCE, [STATUS], PRODUCT_CD FROM ACCOUNT WHERE PRODUCT_CD = 'C%'

SELECT ACCOUNT_ID, AVAIL_BALANCE, [STATUS], PRODUCT_CD FROM ACCOUNT WHERE PRODUCT_CD LIKE 'C%'

SELECT ACCOUNT_ID, AVAIL_BALANCE, [STATUS], PRODUCT_CD FROM ACCOUNT WHERE PRODUCT_CD LIKE '%K'

SELECT PRODUCT_CD, SUM(AVAIL_BALANCE), COUNT(AVAIL_BALANCE), AVG(AVAIL_BALANCE), MIN(AVAIL_BALANCE), MAX(AVAIL_BALANCE)
FROM ACCOUNT WHERE AVAIL_BALANCE >= 500 GROUP BY PRODUCT_CD HAVING COUNT(AVAIL_BALANCE) > 3

SELECT PRODUCT_CD, COUNT(AVAIL_BALANCE)  FROM ACCOUNT WHERE AVAIL_BALANCE >= 500 GROUP BY PRODUCT_CD

SELECT PRODUCT_CD, AVG(AVAIL_BALANCE) TOAN FROM ACCOUNT WHERE AVAIL_BALANCE >= 500 GROUP BY PRODUCT_CD


SELECT PRODUCT_CD, SUM(AVAIL_BALANCE), COUNT(AVAIL_BALANCE), AVG(AVAIL_BALANCE), MIN(AVAIL_BALANCE), MAX(AVAIL_BALANCE)
FROM ACCOUNT a WHERE AVAIL_BALANCE >= 500 GROUP BY PRODUCT_CD HAVING COUNT(AVAIL_BALANCE) > 3

select * from CUSTOMER

SELECT * FROM ACCOUNT 

select * from CUSTOMER
JOIN ACCOUNT ON   CUSTOMER.CUST_ID = ACCOUNT.CUST_ID

select CUSTOMER.[ADDRESS], ACCOUNT.PRODUCT_CD from CUSTOMER
JOIN ACCOUNT ON   CUSTOMER.CUST_ID = ACCOUNT.CUST_ID

select a.[ADDRESS], b.PRODUCT_CD, a.CUST_ID, b.CUST_ID from CUSTOMER a
JOIN ACCOUNT b ON  a.CUST_ID = b.CUST_ID

INSERT INTO [dbo].[CUSTOMER]
           ([ADDRESS]
           ,[CITY]
           ,[CUST_TYPE_CD]
           ,[FED_ID]
           ,[POSTAL_CODE]
           ,[STATE])
     VALUES
           ('TANHOA',
            'DONGTHAP',
           'D',
           '111-11-1111',
           'ABC',
           'XYZ')
GO

select a.[ADDRESS], b.PRODUCT_CD, a.CUST_ID, b.CUST_ID from CUSTOMER a
LEFT JOIN ACCOUNT b ON  a.CUST_ID = b.CUST_ID

select a.[ADDRESS], b.PRODUCT_CD, a.CUST_ID, b.CUST_ID from CUSTOMER a
RIGHT JOIN ACCOUNT b ON  a.CUST_ID = b.CUST_ID

select a.[ADDRESS], b.PRODUCT_CD, a.CUST_ID, b.CUST_ID from CUSTOMER a
LEFT JOIN ACCOUNT b ON  a.CUST_ID = b.CUST_ID WHERE b.CUST_ID IS NULL