/* Bca tbj cso dul sfi 3 - Bai tap co so du lieu so 3.
Ica 26/11/2006, Tbs: Zng Tfy, Tcc: Kos Gre.
Mha ads teh seo lec hcr alxkhi@yahoo.com - Moi chi tiet xin lien he alxkhi@yahoo.com.
*/
--> Sfs, tbs lcc cso dul ALXKHI - Xoa, tao lai co so du lieu ALXKHI.
USE MASTER
GO

IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'ALXKHI')
DROP DATABASE ALXKHI
GO

CREATE DATABASE ALXKHI
GO

--> Yeh lbj cfa I-Y-N - Thiet lap kieu ngay thang nam.
SET DATEFORMAT DMY
GO

--> Dka ALXKHI, tbs cbk bau dul - Dung ALXKHI, tao cac bang du lieu.
USE ALXKHI
GO

--> Bau NHANVIEN
CREATE TABLE NHANVIEN
(
	HONV	VARCHAR (12)	NULL,
	TENLOT	VARCHAR (12)	NULL,
	TENNV	VARCHAR (12)	NULL,
	MANV	VARCHAR (12)	NOT NULL,
	NGSINH	DATETIME	NULL,
	DCHI	VARCHAR (50)	NULL,
	PHAI	VARCHAR (3)	NULL,
	LUONG	INT		NULL,
	MA_NQL	VARCHAR (12)	NULL,
	PHG	VARCHAR (12)	NULL,
CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
GO

--> Bau PHONGBAN
CREATE TABLE PHONGBAN
(
	TENPHG		VARCHAR (12)	NULL,
	MAPHG		VARCHAR (12)	NOT NULL,
	TRPHG		VARCHAR (12)	NULL,
	NG_NHANCHUC	DATETIME	NULL,
CONSTRAINT PK_PHONGBAN PRIMARY KEY (MAPHG)
)
GO

--> Bau DIADIEM_PHG
CREATE TABLE DIADIEM_PHG
(
	MAPHG	VARCHAR (12)	NOT NULL,
	DIADIEM	VARCHAR (12)	NOT NULL,
CONSTRAINT PK_DIADIEM_PHG PRIMARY KEY (MAPHG, DIADIEM)
)
GO

--> Bau DEAN
CREATE TABLE DEAN
(
	TENDA		VARCHAR (12)	NULL,
	MADA		VARCHAR (12)	NOT NULL,
	DDIEM_DA	VARCHAR (12)	NULL,
	PHONG		VARCHAR (12)	NULL,
CONSTRAINT PK_DEAN PRIMARY KEY (MADA)
)
GO

--> Bau THANNHAN
CREATE TABLE THANNHAN
(
	MA_NVIEN	VARCHAR (12)	NOT NULL,
	TENTN		VARCHAR (12)	NOT NULL,
	PHAI		VARCHAR (3)	NULL,
	NGSINH		DATETIME	NULL,
	QUANHE		VARCHAR (12)	NULL,
CONSTRAINT PK_THANNHAN PRIMARY KEY (MA_NVIEN, TENTN)
)
GO

--> Bau PHANCONG
CREATE TABLE PHANCONG
(
	MA_NVIEN	VARCHAR (12)	NOT NULL,
	SODA		VARCHAR (12)	NOT NULL,
	THOIGIAN	REAL	NULL,
CONSTRAINT PK_PHANCONG PRIMARY KEY (MA_NVIEN, SODA)
)
GO

--> Tbs cbk efs igo - Tao cac khoa ngoai.
--> Bau NHANVIEN
ALTER TABLE NHANVIEN ADD
CONSTRAINT FK_NHANVIEN_PHG FOREIGN KEY (PHG)
REFERENCES PHONGBAN (MAPHG),
CONSTRAINT FK_NHANVIEN_MA_NQL FOREIGN KEY (MA_NQL)
REFERENCES NHANVIEN (MANV)
GO

--> Bau PHONGBAN
ALTER TABLE PHONGBAN ADD
CONSTRAINT FK_PHONGBAN FOREIGN KEY (TRPHG)
REFERENCES NHANVIEN (MANV)
GO

--> Bau DIADIEM_PHG
ALTER TABLE DIADIEM_PHG ADD
CONSTRAINT FK_DIADIEM_PHG FOREIGN KEY (MAPHG)
REFERENCES PHONGBAN (MAPHG)
GO

--> Bau DEAN
ALTER TABLE DEAN ADD
CONSTRAINT FK_DEAN_PHONG FOREIGN KEY (PHONG)
REFERENCES PHONGBAN (MAPHG),
CONSTRAINT FK_DEAN_DDP FOREIGN KEY (PHONG, DDIEM_DA)
REFERENCES DIADIEM_PHG (MAPHG, DIADIEM)
GO

--> Bau PHANCONG
ALTER TABLE PHANCONG ADD
CONSTRAINT FK_MA_NVIEN FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV),
CONSTRAINT FK_SODA FOREIGN KEY (SODA)
REFERENCES DEAN (MADA)
GO

--> Bau THANNHAN
ALTER TABLE THANNHAN ADD
CONSTRAINT FK_MA_NVIEN_TN FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)
GO

--> Obj dul afc cbk bau - Nhap du lieu cho cac bang.
--> Bau NHANVIEN
INSERT INTO NHANVIEN
VALUES ('DINH', 'BA', 'TIEN', '123456789', '9/1/1975', '731 TRAN HUNG DAO Q1, TPHCM', 'NAM', 30000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES('NGUYEN', 'THANH', 'TUNG', '333445555', '9/12/1945', '638 NGUYEN VAN CU Q5, TPHCM', 'NAM', 40000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('BUI', 'THUY', 'VU', '999887777', '19/7/1958', '332 NGUYEN THAI HOC Q1,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('LE', 'THI', 'NHAN', '987654321', '20/6/1931', '291 HO VAN HUE QPN,  TPHCM', 'NU', 43000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('NGUYEN', 'MANH', 'HUNG', '666884444', '15/9/1952', '975 BA RIA VUNG TAU', 'NAM', 38000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('TRAN', 'THANH', 'TAM', '453453453', '31/7/1972', '543 MAI THI LUU Q1,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('TRAN', 'HONG', 'QUANG', '987987987', '29/3/1979', '980 LE HONG PHONG Q10,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('VUONG', 'NGOC', 'QUYEN', '888665555', '10/10/1964', '450 TRUNG VUONG,  HA NOI', 'NU', 55000, NULL, NULL)
GO

--> Bau PHONGBAN
INSERT INTO PHONGBAN
VALUES ('NGHIEN CUU', '5', '333445555', '22/5/1978')
GO

INSERT INTO PHONGBAN
VALUES ('DIEU HANH', '4', '987987987', '1/1/1985')
GO

INSERT INTO PHONGBAN
VALUES ('QUAN LI', '1', '888665555', '19/6/1971')
GO

--> Cbj obn dul afc bau NHANVIEN - Cap nhat du lieu cho ban NHANVIEN.
UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '123456789'
GO

UPDATE NHANVIEN
SET MA_NQL = '888665555', PHG = '5'
WHERE MANV LIKE '333445555'
GO

UPDATE NHANVIEN
SET MA_NQL = '987654321', PHG = '4'
WHERE MANV LIKE '999887777'
GO

UPDATE NHANVIEN
SET MA_NQL = '888665555', PHG = '4'
WHERE MANV LIKE '987654321'
GO

UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '666884444'
GO

UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '453453453'
GO

UPDATE NHANVIEN
SET MA_NQL = '987654321', PHG = '4'
WHERE MANV LIKE '987987987'
GO

UPDATE NHANVIEN
SET PHG = '1'
WHERE MANV LIKE '888665555'
GO

--> Bau DIADIEM_PHG
INSERT INTO DIADIEM_PHG
VALUES ('1', 'TP HCM')
GO

INSERT INTO DIADIEM_PHG
VALUES ('4', 'HA NOI')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'VUNG TAU')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'NHA TRANG')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'TP HCM')
GO

--> Bau DEAN
INSERT INTO DEAN
VALUES ('SAN PHAM X', '1', 'VUNG TAU', '5')
GO

INSERT INTO DEAN
VALUES ('SAN PHAM Y', '2', 'NHA TRANG', '5')
GO

INSERT INTO DEAN
VALUES ('SAN PHAM Z', '3', 'TP HCM', '5')
GO

INSERT INTO DEAN
VALUES ('TIN HOC HOA', '10', 'HA NOI', '4')
GO

INSERT INTO DEAN
VALUES ('CAP QUANG', '20', 'TP HCM', '1')
GO

INSERT INTO DEAN
VALUES ('DAO TAO', '30', 'HA NOI', '4')
GO

--> Bau THANNHAN
INSERT INTO THANNHAN
VALUES ('333445555', 'QUANG', 'NU', '5/4/1976', 'CON GAI')
GO

INSERT INTO THANNHAN
VALUES ('333445555', 'KHANG', 'NAM', '25/10/1973', 'CON TRAI')
GO

INSERT INTO THANNHAN
VALUES ('333445555', 'DUONG', 'NU', '3/5/1948', 'VO CHONG')
GO

INSERT INTO THANNHAN
VALUES ('987654321', 'DANG', 'NAM', '29/2/1932', 'VO CHONG')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'DUY', 'NAM', '1/1/1978', 'CON TRAI')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'CHAU', 'NU', '31/12/1978', 'CON GAI')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'PHUONG', 'NU', '5/5/1957', 'VO CHONG')
GO

--> Bau PHANCONG
INSERT INTO PHANCONG
VALUES ('123456789', '1', 32.5)
GO

INSERT INTO PHANCONG
VALUES ('123456789', '2', 7.5)
GO

INSERT INTO PHANCONG
VALUES ('666884444', '3', 40.5)
GO

INSERT INTO PHANCONG
VALUES ('453453453', '1', 20.5)
GO

INSERT INTO PHANCONG
VALUES ('453453453', '2', 20)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '3', 10)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '10', 10)
GO

INSERT INTO PHANCONG
VALUES ('999887777', '30', 30)
GO

INSERT INTO PHANCONG
VALUES ('999887777', '10', 10)
GO

INSERT INTO PHANCONG
VALUES ('987987987', '10', 35)
GO

INSERT INTO PHANCONG
VALUES ('987987987', '30', 5)
GO

INSERT INTO PHANCONG
VALUES ('987654321', '30', 20)
GO

INSERT INTO PHANCONG
VALUES ('987654321', '20', 15)
GO

INSERT INTO PHANCONG
VALUES ('888665555', '20', NULL)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '20', 10)
GO

--> Alo vax dul - Truy van du lieu.
--> Cbt 01
--| A = SODA S SUM (THOIGIAN) AS TTG (PHANCONG)
--|	  MADA = SODA
--| Q = DEAN |><| A [TENDA, TTG]
SELECT TENDA, TTG FROM DEAN,
	(SELECT SODA, SUM (THOIGIAN) AS TTG FROM PHANCONG
	GROUP BY SODA) AS A
WHERE DEAN. MADA = A. SODA
GO

--> Cbt 02
--| A = PHG S AVG (LUONG) AS LTB (NHANVIEN)
--|	     MAPHG = PHG
--| Q = PHONGBAN |><| A [TENPHG, LTB]
SELECT TENPHG, LTB FROM PHONGBAN,
	(SELECT PHG, AVG (LUONG) AS LTB FROM NHANVIEN
	GROUP BY PHG) AS A
WHERE PHONGBAN. MAPHG = A.PHG
GO

--> Cbt 03
--| A = PHG S AVG (LUONG), COUNT (MANV) AS SLNV (NHANVIEN): AVG (LUONG) > 30000
--|	     MAPHG = PHG
--| Q = PHONGBAN |><| A [TENPHG, SLNV]
SELECT TENPHG, SLNV FROM PHONGBAN,
	(SELECT PHG, COUNT (MANV) AS SLNV FROM NHANVIEN
	GROUP BY PHG
	HAVING AVG (LUONG) > 30000) AS A
WHERE PHONGBAN. MAPHG = A.PHG
GO

--> Cbt 04
--| A = PHG S COUNT (MANV) AS SLNV (NHANVIEN)
--| Q1 = S MAX (SLNV) (A)
--| B = PHG S COUNT (MANV) (NHANVIEN): COUNT (MANV) IN Q1
--|	     MANV = TRPHG   PHG = MAPHG
--| Q = (NHANVIEN |><| PHONGBAN) |><| B [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], TENPHG FROM NHANVIEN, PHONGBAN,
	(SELECT PHG FROM NHANVIEN
	GROUP BY PHG
	HAVING COUNT (MANV) IN
		(SELECT MAX (SLNV) AS MSL FROM
			(SELECT PHG, COUNT (MANV) AS SLNV FROM NHANVIEN
			GROUP BY PHG) AS A)) AS B
WHERE NHANVIEN. MANV = PHONGBAN. TRPHG
AND B. PHG = PHONGBAN. MAPHG
GO

--> Cbt 05
--|	    MANV = TRPHG
--| Q = NHANVIEN |><| PHONGBAN [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], TENPHG FROM NHANVIEN, PHONGBAN
WHERE NHANVIEN. MANV = PHONGBAN. TRPHG

--> Cbt 06
--| A = NHANVIEN TOP 3 [MANV, YEAR ( GETDATE ()) - YEAR (NGSINH) AS TUOI] ORDER BY TUOI DESC
--|	     MANV = MANV
--| Q = NHANVIEN |><| A [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN,
	(SELECT TOP 3 MANV, YEAR ( GETDATE ()) - YEAR (NGSINH) AS TUOI FROM NHANVIEN
	ORDER BY TUOI DESC) AS A
WHERE NHANVIEN. MANV = A. MANV
GO

--> Cbt 07
--| R = PHANCONG [MA_NVIEN, SODA]				|
--| S = DEAN [MADA]						|
--| Q1 = R / S [MA_NVIEN]					|(?)
--|	    MANV = MA_NVIEN					|
--| Q = NHANVIEN |><| Q1 [HONV + ' ' + TENLOT + ' ' + TENNV]	|
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE NOT EXISTS
	(SELECT * FROM DEAN
	WHERE NOT EXISTS
		(SELECT * FROM PHANCONG
		WHERE NHANVIEN. MANV = PHANCONG. MA_NVIEN
		AND DEAN. MADA = PHANCONG. SODA))
GO

--> Dul fcq yiq cbt 07 - Du lieu de thu cau 07.
INSERT INTO PHANCONG
VALUES ('123456789', '3', 75.5)
GO

INSERT INTO PHANCONG
VALUES ('123456789', '10', 55.4)
GO

INSERT INTO PHANCONG
VALUES ('123456789', '20', 4.5)
GO
INSERT INTO PHANCONG
VALUES ('123456789', '30', 7.9)
GO

--> Alk bav hgq tie! - Chuc ban hoc tot!