/* Bca tbj cso dul sfi 3 - Bai tap co so du lieu so 3.
Ica 26/11/2006, Tbs: Zng Tfy, Tcc: Kos Gre.
Mha ads teh seo lec hcr alxkhi@yahoo.com - Moi chi tiet xin lien he alxkhi@yahoo.com.
*/
--> Sfs, tbs lcc cso dul ALXKHI - Xoa, tao lai co so du lieu ALXKHI.
USE MASTER
GO

IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'ALXKHI')
DROP DATABASE ALXKHI
GO

CREATE DATABASE ALXKHI
GO

--> Yeh lbj cfa I-Y-N - Thiet lap kieu ngay thang nam.
SET DATEFORMAT DMY
GO

--> Dka ALXKHI, tbs cbk bau dul - Dung ALXKHI, tao cac bang du lieu.
USE ALXKHI
GO

--> Bau NHANVIEN
CREATE TABLE NHANVIEN
(
	HONV	VARCHAR (12)	NULL,
	TENLOT	VARCHAR (12)	NULL,
	TENNV	VARCHAR (12)	NULL,
	MANV	VARCHAR (12)	NOT NULL,
	NGSINH	DATETIME	NULL,
	DCHI	VARCHAR (50)	NULL,
	PHAI	VARCHAR (3)	NULL,
	LUONG	INT		NULL,
	MA_NQL	VARCHAR (12)	NULL,
	PHG	VARCHAR (12)	NULL,
CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
GO

--> Bau PHONGBAN
CREATE TABLE PHONGBAN
(
	TENPHG		VARCHAR (12)	NULL,
	MAPHG		VARCHAR (12)	NOT NULL,
	TRPHG		VARCHAR (12)	NULL,
	NG_NHANCHUC	DATETIME	NULL,
CONSTRAINT PK_PHONGBAN PRIMARY KEY (MAPHG)
)
GO

--> Bau DIADIEM_PHG
CREATE TABLE DIADIEM_PHG
(
	MAPHG	VARCHAR (12)	NOT NULL,
	DIADIEM	VARCHAR (12)	NOT NULL,
CONSTRAINT PK_DIADIEM_PHG PRIMARY KEY (MAPHG, DIADIEM)
)
GO

--> Bau DEAN
CREATE TABLE DEAN
(
	TENDA		VARCHAR (12)	NULL,
	MADA		VARCHAR (12)	NOT NULL,
	DDIEM_DA	VARCHAR (12)	NULL,
	PHONG		VARCHAR (12)	NULL,
CONSTRAINT PK_DEAN PRIMARY KEY (MADA)
)
GO

--> Bau THANNHAN
CREATE TABLE THANNHAN
(
	MA_NVIEN	VARCHAR (12)	NOT NULL,
	TENTN		VARCHAR (12)	NOT NULL,
	PHAI		VARCHAR (3)	NULL,
	NGSINH		DATETIME	NULL,
	QUANHE		VARCHAR (12)	NULL,
CONSTRAINT PK_THANNHAN PRIMARY KEY (MA_NVIEN, TENTN)
)
GO

--> Bau PHANCONG
CREATE TABLE PHANCONG
(
	MA_NVIEN	VARCHAR (12)	NOT NULL,
	SODA		VARCHAR (12)	NOT NULL,
	THOIGIAN	REAL	NULL,
CONSTRAINT PK_PHANCONG PRIMARY KEY (MA_NVIEN, SODA)
)
GO

--> Tbs cbk efs igo - Tao cac khoa ngoai.
--> Bau NHANVIEN
ALTER TABLE NHANVIEN ADD
CONSTRAINT FK_NHANVIEN_PHG FOREIGN KEY (PHG)
REFERENCES PHONGBAN (MAPHG),
CONSTRAINT FK_NHANVIEN_MA_NQL FOREIGN KEY (MA_NQL)
REFERENCES NHANVIEN (MANV)
GO

--> Bau PHONGBAN
ALTER TABLE PHONGBAN ADD
CONSTRAINT FK_PHONGBAN FOREIGN KEY (TRPHG)
REFERENCES NHANVIEN (MANV)
GO

--> Bau DIADIEM_PHG
ALTER TABLE DIADIEM_PHG ADD
CONSTRAINT FK_DIADIEM_PHG FOREIGN KEY (MAPHG)
REFERENCES PHONGBAN (MAPHG)
GO

--> Bau DEAN
ALTER TABLE DEAN ADD
CONSTRAINT FK_DEAN_PHONG FOREIGN KEY (PHONG)
REFERENCES PHONGBAN (MAPHG),
CONSTRAINT FK_DEAN_DDP FOREIGN KEY (PHONG, DDIEM_DA)
REFERENCES DIADIEM_PHG (MAPHG, DIADIEM)
GO

--> Bau PHANCONG
ALTER TABLE PHANCONG ADD
CONSTRAINT FK_MA_NVIEN FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV),
CONSTRAINT FK_SODA FOREIGN KEY (SODA)
REFERENCES DEAN (MADA)
GO

--> Bau THANNHAN
ALTER TABLE THANNHAN ADD
CONSTRAINT FK_MA_NVIEN_TN FOREIGN KEY (MA_NVIEN)
REFERENCES NHANVIEN (MANV)
GO

--> Obj dul afc cbk bau - Nhap du lieu cho cac bang.
--> Bau NHANVIEN
INSERT INTO NHANVIEN
VALUES ('DINH', 'BA', 'TIEN', '123456789', '9/1/1975', '731 TRAN HUNG DAO Q1, TPHCM', 'NAM', 30000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES('NGUYEN', 'THANH', 'TUNG', '333445555', '9/12/1945', '638 NGUYEN VAN CU Q5, TPHCM', 'NAM', 40000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('BUI', 'THUY', 'VU', '999887777', '19/7/1958', '332 NGUYEN THAI HOC Q1,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('LE', 'THI', 'NHAN', '987654321', '20/6/1931', '291 HO VAN HUE QPN,  TPHCM', 'NU', 43000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('NGUYEN', 'MANH', 'HUNG', '666884444', '15/9/1952', '975 BA RIA VUNG TAU', 'NAM', 38000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('TRAN', 'THANH', 'TAM', '453453453', '31/7/1972', '543 MAI THI LUU Q1,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('TRAN', 'HONG', 'QUANG', '987987987', '29/3/1979', '980 LE HONG PHONG Q10,  TPHCM', 'NAM', 25000, NULL, NULL)
GO

INSERT INTO NHANVIEN
VALUES ('VUONG', 'NGOC', 'QUYEN', '888665555', '10/10/1964', '450 TRUNG VUONG,  HA NOI', 'NU', 55000, NULL, NULL)
GO

--> Bau PHONGBAN
INSERT INTO PHONGBAN
VALUES ('NGHIEN CUU', '5', '333445555', '22/5/1978')
GO

INSERT INTO PHONGBAN
VALUES ('DIEU HANH', '4', '987987987', '1/1/1985')
GO

INSERT INTO PHONGBAN
VALUES ('QUAN LI', '1', '888665555', '19/6/1971')
GO

--> Cbj obn dul afc bau NHANVIEN - Cap nhat du lieu cho ban NHANVIEN.
UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '123456789'
GO

UPDATE NHANVIEN
SET MA_NQL = '888665555', PHG = '5'
WHERE MANV LIKE '333445555'
GO

UPDATE NHANVIEN
SET MA_NQL = '987654321', PHG = '4'
WHERE MANV LIKE '999887777'
GO

UPDATE NHANVIEN
SET MA_NQL = '888665555', PHG = '4'
WHERE MANV LIKE '987654321'
GO

UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '666884444'
GO

UPDATE NHANVIEN
SET MA_NQL = '333445555', PHG = '5'
WHERE MANV LIKE '453453453'
GO

UPDATE NHANVIEN
SET MA_NQL = '987654321', PHG = '4'
WHERE MANV LIKE '987987987'
GO

UPDATE NHANVIEN
SET PHG = '1'
WHERE MANV LIKE '888665555'
GO

--> Bau DIADIEM_PHG
INSERT INTO DIADIEM_PHG
VALUES ('1', 'TP HCM')
GO

INSERT INTO DIADIEM_PHG
VALUES ('4', 'HA NOI')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'VUNG TAU')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'NHA TRANG')
GO

INSERT INTO DIADIEM_PHG
VALUES ('5', 'TP HCM')
GO

--> Bau DEAN
INSERT INTO DEAN
VALUES ('SAN PHAM X', '1', 'VUNG TAU', '5')
GO

INSERT INTO DEAN
VALUES ('SAN PHAM Y', '2', 'NHA TRANG', '5')
GO

INSERT INTO DEAN
VALUES ('SAN PHAM Z', '3', 'TP HCM', '5')
GO

INSERT INTO DEAN
VALUES ('TIN HOC HOA', '10', 'HA NOI', '4')
GO

INSERT INTO DEAN
VALUES ('CAP QUANG', '20', 'TP HCM', '1')
GO

INSERT INTO DEAN
VALUES ('DAO TAO', '30', 'HA NOI', '4')
GO

--> Bau THANNHAN
INSERT INTO THANNHAN
VALUES ('333445555', 'QUANG', 'NU', '5/4/1976', 'CON GAI')
GO

INSERT INTO THANNHAN
VALUES ('333445555', 'KHANG', 'NAM', '25/10/1973', 'CON TRAI')
GO

INSERT INTO THANNHAN
VALUES ('333445555', 'DUONG', 'NU', '3/5/1948', 'VO CHONG')
GO

INSERT INTO THANNHAN
VALUES ('987654321', 'DANG', 'NAM', '29/2/1932', 'VO CHONG')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'DUY', 'NAM', '1/1/1978', 'CON TRAI')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'CHAU', 'NU', '31/12/1978', 'CON GAI')
GO

INSERT INTO THANNHAN
VALUES ('123456789', 'PHUONG', 'NU', '5/5/1957', 'VO CHONG')
GO

--> Bau PHANCONG
INSERT INTO PHANCONG
VALUES ('123456789', '1', 32.5)
GO

INSERT INTO PHANCONG
VALUES ('123456789', '2', 7.5)
GO

INSERT INTO PHANCONG
VALUES ('666884444', '3', 40.5)
GO

INSERT INTO PHANCONG
VALUES ('453453453', '1', 20.5)
GO

INSERT INTO PHANCONG
VALUES ('453453453', '2', 20)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '3', 10)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '10', 10)
GO

INSERT INTO PHANCONG
VALUES ('999887777', '30', 30)
GO

INSERT INTO PHANCONG
VALUES ('999887777', '10', 10)
GO

INSERT INTO PHANCONG
VALUES ('987987987', '10', 35)
GO

INSERT INTO PHANCONG
VALUES ('987987987', '30', 5)
GO

INSERT INTO PHANCONG
VALUES ('987654321', '30', 20)
GO

INSERT INTO PHANCONG
VALUES ('987654321', '20', 15)
GO

INSERT INTO PHANCONG
VALUES ('888665555', '20', NULL)
GO

INSERT INTO PHANCONG
VALUES ('333445555', '20', 10)
GO

--> Alo vax dul - Truy van du lieu.
--> Cbt 01
--| Q = NHANVIEN: DCHI LIKE '%TPHCM%' [HONV + ' ' + TENLOT + ' ' + TENNV, DCHI]
--| ORDER BY TENNV, TENLOT, HONV
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN
WHERE DCHI LIKE '%TPHCM%'
ORDER BY TENNV, TENLOT, HONV
GO

--> Cbt 02
--| Q = NHANVIEN: YEAR (GETDATE ()) - YEAR (NGSINH) > 40
--| [HONV + ' ' + TENLOT + ' ' + TENNV, LUONG] ORDER BY TENNV, TENLOT, HONV
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], LUONG FROM NHANVIEN
WHERE YEAR (GETDATE ()) - YEAR (NGSINH) > 40
ORDER BY TENNV, TENLOT, HONV
GO

--> Cbt 03
--|	     MANV = MA_NVIEN
--| Q = (NHANVIEN |><| THANNHAN) [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN, THANNHAN
WHERE MANV = MA_NVIEN
AND TENNV = TENTN
GO

--> Cbt 04
--|	      MANV = TRPHG   MAPHG = PHONG
--| Q = ((NHANVIEN |><| PHONGBAN) |><| DEAN): DDIEM_DA = 'HA NOI'
--| [MADA, TENPHG , HONV + ' ' + TENLOT + ' ' + TENNV, DCHI, NGSINH]
SELECT MADA, TENPHG , HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI, NGSINH
FROM NHANVIEN, DEAN, PHONGBAN
WHERE DDIEM_DA = 'HA NOI'
AND NHANVIEN. MANV = PHONGBAN. TRPHG
AND PHONGBAN. MAPHG = DEAN. PHONG
GO

--> Cbt 05
--|	     MANV = MA_NVIEN  SODA = MADA
--| Q = ((NHANVIEN |><| PHANCONG) |><| DEAN): PHG = '5' AND TENDA = 'SAN PHAM X'
--| AND THOIGIAN > 10 [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN, DEAN, PHANCONG
WHERE PHG = '5'
AND TENDA = 'SAN PHAM X'
AND THOIGIAN > 10
AND NHANVIEN. MANV = PHANCONG. MA_NVIEN
AND PHANCONG. SODA = DEAN. MADA
GO

--> Cbt 06
--> Caf 1
--| Q1 = THANNHAN [MA_NVIEN]
--| Q = NHANVIEN: MANV NOT IN Q1 [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE MANV NOT IN
	(SELECT MA_NVIEN FROM THANNHAN)
GO

--> Caf 2
--|	    MANV = MA_NVIEN
--| Q = NHANVIEN ||><| THANNHAN: MA_NVIEN IS NULL
--| [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN LEFT JOIN THANNHAN
ON NHANVIEN. MANV = THANNHAN. MA_NVIEN
WHERE MA_NVIEN IS NULL
GO

--> Caf 3
--| Q = THANNHAN |><|| NHANVIEN: MA_NVIEN IS NULL
--| [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM THANNHAN RIGHT JOIN NHANVIEN
ON NHANVIEN. MANV = THANNHAN. MA_NVIEN
WHERE MA_NVIEN IS NULL
GO

--> Caf 4
--| R = THANNHAN [MA_NVIEN]
--| S = NHANVIEN [MANV]
--| Q1 = S \ R [MANV]
--|	     MANV = MANV
--| Q = NHANVIEN |><| Q1 [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE NOT EXISTS
	(SELECT * FROM THANNHAN
	WHERE NHANVIEN. MANV = THANNHAN. MA_NVIEN)

--> Cbt 07
--|				  TRPHG = MA_NVIEN
--| Q1 = MA_NVIEN S COUNT (*) (PHONGBAN |><| THANNHAN): COUNT (*) >= 1
--| Q = NHANVIEN: MANV IN Q1 [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE MANV IN
	(SELECT MA_NVIEN FROM PHONGBAN, THANNHAN
	WHERE PHONGBAN. TRPHG = THANNHAN. MA_NVIEN
	GROUP BY MA_NVIEN
	HAVING COUNT (*) >= 1)
GO

--> Cbt 08
--| Q1 = PHANCONG [MA_NVIEN]
--| Q = NHANVIEN: MANV NOT IN Q1 [HONV + ' ' + TENLOT + ' ' + TENNV]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE MANV NOT IN
	(SELECT MA_NVIEN FROM PHANCONG)
GO
SELECT * FROM PHAN
--> Dul yiq cbt 08 - Du lieu thu cau 08.
INSERT INTO NHANVIEN
VALUES ('NGUYEN', 'ANH', 'TUC', '190012340', '1/1/1988', 'SYN FON 12, KOS GRE, ZNG', 'NU', 34000, '333445555', '1')
GO

--> Cbt 09
--| Q1 = MA_NVIEN S COUNT (*) (THANNHAN): COUNT (*) >= 2
--| Q = NHANVIEN: MANV IN Q1
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN] FROM NHANVIEN
WHERE MANV IN
	(SELECT MA_NVIEN FROM THANNHAN
	GROUP BY MA_NVIEN
	HAVING COUNT (*) >= 2)
GO

--> Cbt 10
--|	     PHG = MAPHG
--| Q = NHANVIEN |><| PHONGBAN: TENPHG = 'NGHIEN CUU'
--| [HONV + ' ' + TENLOT + ' ' + TENNV, DCHI]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN, PHONGBAN
WHERE TENPHG = 'NGHIEN CUU'
AND NHANVIEN. PHG = PHONGBAN. MAPHG
GO

--> Cbt 11
--| Q1 = NHANVIEN: HONV + ' ' + TENLOT + ' ' + TENNV = 'NGUYEN THANH TUNG' [MANV]
--| Q = NHANVIEN: MA_NQL IN Q1 [HONV + ' ' + TENLOT + ' ' + TENNV, DCHI]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN
WHERE MA_NQL IN
	(SELECT MANV FROM NHANVIEN
	WHERE HONV + ' ' + TENLOT + ' ' + TENNV = 'NGUYEN THANH TUNG')
GO

--> Cbt 12
--> Caf 1
--|		PHG = MAPHG
--| Q1 = NHANVIEN |><| DIADIEM_PHG: DIADIEM = 'TP HCM' [MANV]
--| B = NHANVIEN: MANV NOT IN Q1 [MANV]
--|	      SODA = MADA
--| A = PHANCONG |><| DEAN: DDIEM_DA = 'TPHCM' [MA_NVIEN]
--|   MA_NVIEN = MANV
--| Q2 = A |><| B [MANV]
--| Q = NHANVIEN: MANV IN Q2 [HONV + ' ' + TENLOT + ' ' + TENNV, DCHI]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN
WHERE MANV IN
	(SELECT B. MANV FROM (SELECT MA_NVIEN FROM PHANCONG, DEAN
		WHERE PHANCONG. SODA = DEAN. MADA
		AND DDIEM_DA = 'TP HCM') AS A,
		(SELECT MANV FROM NHANVIEN
		WHERE MANV NOT IN
			(SELECT MANV FROM NHANVIEN, DIADIEM_PHG
			WHERE NHANVIEN. PHG = DIADIEM_PHG. MAPHG
			AND DIADIEM = 'TP HCM')) AS B
	WHERE A. MA_NVIEN = B. MANV)
GO

--> Caf 2
--|		MANV = MA_NVIEN	SODA = MADA
--| Q1 = ((NHANVIEN |><| PHANCONG) |><| DEAN): DDIEM_DA = 'TP HCM' [NHANVIEN. *]
--| Q2 = Q1: PHG NOT IN Q3 [*]
--| Q3 = DDIEM_PHG: DIADIEM = 'TP HCM' [MAPHG]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN, PHANCONG, DEAN
WHERE DDIEM_DA = 'TP HCM'
AND NHANVIEN. MANV = PHANCONG. MA_NVIEN
AND PHANCONG. SODA = DEAN. MADA
AND PHG NOT IN
	(SELECT MAPHG FROM DIADIEM_PHG
	WHERE DIADIEM = 'TP HCM')
GO

--> Cbt 13
--|		MANV = MA_NVIEN	SODA = MADA
--| Q1 = ((NHANVIEN |><| PHANCONG) |><| DEAN) [NHANVIEN. *]
--| X = DEAN [DDIEM_DA]
--| Q2 = DDIEM_PHG: DIADIEM = X [MAPHG]
--| Q = Q1: PHG NOT IN Q2 [*]
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS [HO TEN], DCHI FROM NHANVIEN, PHANCONG, DEAN
WHERE NHANVIEN.MANV = PHANCONG.MA_NVIEN
AND PHANCONG.SODA = DEAN.MADA
AND PHG NOT IN
	(SELECT MAPHG FROM DIADIEM_PHG
	WHERE DIADIEM = DDIEM_DA)

--> Alk bav hgq tie! - Chuc ban hoc tot!